---
apiVersion: batch/v1
kind: Job
metadata:
  name: html-scraper
spec:
  template:
    spec:
      containers:
        - name: scraper-main
          image: html-scraper
          # FOR LOCAL CLUSTER:
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 5s
              trap "touch /tmp/shared/exited" EXIT
              python /home/selenium/main.py
          env:
            - name: VUOKRAOVI_URL
              value: "http://dev-vuokraovi-app"
            - name: SELENIUM_URL
              value: "http://localhost:4444/wd/hub"
          volumeMounts:
            - mountPath: /tmp/shared
              name: tmp-shared
            - mountPath: /data
              name: data
        - name: seleniumserver
          image: seleniumserver-sidecar
          # FOR LOCAL CLUSTER:
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /tmp/shared
              name: tmp-shared
              readOnly: true
      restartPolicy: Never
      initContainers:
        - name: init-html-db
          image: sqlite-db-creator
          # FOR LOCAL CLUSTER:
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: tmp-shared
          emptyDir: {}
        - name: data
          persistentVolumeClaim:
            claimName: html-db-claim
  backoffLimit: 1
  parallelism: 1
  completions: 1
