# This is for local Kubernetes cluster
# storageClass & hostPath need to be changed for actual deployment
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: html-db-pv
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/private/var/helsinki-houseprice"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: html-db-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
