kind: PersistentVolume
apiVersion: v1
metadata:
  name: html-db-pv
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/private/var/helsinki-houseprice-pv"
