version: '3'
services:
  scraper:
    image: html-scraper
    container_name: html-scraper
    command: sh -c "touch /tmp/keepalive && tail -f /tmp/keepalive"
    volumes: 
      - ./src:/home/selenium
      - ./data:/data
    links:
      - seleniumserver
    depends_on:
      - seleniumserver
  seleniumserver:
    image: selenium/standalone-chrome:3
    ports:
      - "4444:4444"
  db:
    image: sqlite-db-creator
    volumes:
      - ./data:/data
