version: '3'
services:
  scraper:
    image: html-scraper
    container_name: html-scraper
    command: sh -c "touch /tmp/keepalive && tail -f /tmp/keepalive"
    volumes: 
      - ./src:/home/selenium
      - ./data:/data
    links:
      - seleniumserver
    environment:
      - VUOKRAOVI_URL=http://vuokraovi_webapp
    depends_on:
      - seleniumserver
      - db
      - vuokraovi_webapp
  seleniumserver:
    image: selenium/standalone-chrome:3
    links:
      - vuokraovi_webapp
  db:
    image: sqlite-db-creator
    volumes:
      - ./data:/data
  vuokraovi_webapp:
    image: dev-vuokraovi-app
