kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: html-db-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
