---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-vuokraovi-app-v0
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-vuokraovi-app
  template:
    metadata:
      labels:
        app: dev-vuokraovi-app
        version: v0
    spec:
      containers:
      - name: dev-vuokraovi-app
        image: dev-vuokraovi-app
        # FOR LOCAL CLUSTER:
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  name: dev-vuokraovi-app
spec:
  selector:
    app: dev-vuokraovi-app
  ports:
  - name: http
    protocol: TCP
    port: 80
